import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const savedLocale = localStorage.getItem('quizzz.locale');
const detectedLocale = navigator.language?.toLowerCase().startsWith('en') ? 'en' : 'vi';

export const resources = {
  vi: {
    translation: {
      common: { language: 'Ngôn ngữ', vietnamese: 'Tiếng Việt', english: 'English', loading: 'Đang tải...', retry: 'Thử lại', close: 'Đóng', save: 'Lưu', cancel: 'Hủy', errorTitle: 'Có lỗi xảy ra', requestFailed: 'Không thể hoàn tất yêu cầu. Vui lòng thử lại.', guest: 'Khách', changeAccount: 'Đổi tài khoản', signIn: 'Đăng nhập', signOut: 'Đăng xuất', locked: 'Khóa', online: 'Hệ thống hoạt động' },
      navigation: { student: 'Học sinh', teacher: 'Giáo viên', home: 'Trang chủ', room: 'Phòng realtime', assignments: 'Bài tập của tôi', classes: 'Lớp học', classList: 'Danh sách lớp', accounts: 'Quản lý tài khoản', schools: 'Trường học', locations: 'Quản lý tỉnh, xã', typing: 'Luyện gõ 10 ngón', dashboard: 'Tổng quan', questions: 'Kho câu hỏi', ai: 'Tạo câu hỏi AI', quizzes: 'Bộ quiz', worksheets: 'Xuất phiếu Word', reports: 'Báo cáo', admin: 'Quản trị hệ thống', assign: 'Giao bài tập', teacherSignIn: 'Đăng nhập giáo viên' },
      brand: { caption: 'HỌC VUI · NHỚ LÂU', teacherSpace: 'Không gian giáo viên', studentSpace: 'Không gian học sinh', teacherChip: 'GV · {{name}}', studentChip: 'HS · {{name}}' },
      theme: { label: 'Giao diện', light: 'Sáng', dark: 'Tối', useLight: 'Dùng giao diện sáng', useDark: 'Dùng giao diện tối' },
      home: { eyebrow: 'NỀN TẢNG HỌC TẬP TƯƠNG TÁC', title: 'Học vui hơn với mỗi câu hỏi.', description: 'Luyện tập kiến thức, tham gia phòng quiz trực tiếp cùng lớp và nhận kết quả ngay sau mỗi thử thách.', join: 'Tham gia phòng quiz →', learnMore: 'Tìm hiểu thêm', realtimeTitle: 'Chơi realtime', realtimeDescription: 'Tham gia phòng bằng mã giáo viên cung cấp.', practiceTitle: 'Luyện tập chủ động', practiceDescription: 'Ôn lại kiến thức theo môn học và khối lớp.', resultTitle: 'Biết kết quả ngay', resultDescription: 'Xem điểm và tiến bộ sau mỗi lần hoàn thành.' },
      landing: { eyebrow: 'HỌC TẬP TƯƠNG TÁC · MỖI NGÀY TIẾN BỘ', title: 'Chơi quiz. Luyện gõ. Tự tin hơn mỗi ngày.', description: 'Quizzz kết hợp những trận quiz sôi nổi với lộ trình luyện gõ phím trực quan, giúp học sinh học chủ động và giáo viên theo dõi tiến bộ dễ dàng.', quizCta: 'Khám phá quiz', typingCta: 'Luyện gõ phím', cardCaption: 'Học vui · Nhớ lâu', quizBadge: 'Quiz realtime', typingBadge: '10 ngón chuẩn', quizEyebrow: 'CHƠI VÀ HỌC', quizTitle: 'Quiz realtime cùng lớp', quizDescription: 'Tham gia phòng bằng mã, trả lời theo thời gian thực và xem bảng xếp hạng ngay khi trận đấu kết thúc.', quizLink: 'Vào khu vực học sinh', typingEyebrow: 'KỸ NĂNG SỐ', typingTitle: 'Luyện gõ phím 10 ngón', typingDescription: 'Tập từ hàng phím cơ sở đến văn bản thực tế với bàn phím ảo, hướng dẫn bàn tay và thống kê WPM.', typingLink: 'Mở lộ trình luyện gõ', trustOne: 'Học theo nhịp riêng', trustTwo: 'Kết quả trực quan', trustThree: 'Dùng được trên mọi thiết bị' },
      auth: { eyebrow: 'ĐĂNG NHẬP', title: 'Bắt đầu học tập', registerEyebrow: 'ĐĂNG KÝ', registerTitle: 'Tạo tài khoản học sinh', nickname: 'Nickname', nicknamePlaceholder: 'Nhập nickname', username: 'Tên đăng nhập', usernameOrEmail: 'Tên đăng nhập hoặc email', email: 'Email', phone: 'Số điện thoại', password: 'Mật khẩu', confirmPassword: 'Nhập lại mật khẩu', passwordMismatch: 'Mật khẩu nhập lại chưa khớp.', register: 'Đăng ký', haveAccount: 'Đã có tài khoản? Đăng nhập', createAccount: 'Chưa có tài khoản? Đăng ký', loginWithGoogle: 'Đăng nhập với Google', registerWithGoogle: 'Đăng ký với Google' },
      quiz: { allowRetry: 'Cho phép làm lại', showAnswers: 'Hiển thị đáp án sau khi nộp', submit: 'Nộp bài', unanswered: 'Còn {{count}} câu chưa trả lời. Bạn vẫn muốn nộp bài?', answered: 'Đã trả lời {{answered}}/{{total}} câu' },
      ai: { title: 'Tạo câu hỏi bằng AI', generating: 'AI đang tạo câu hỏi...', generatingHint: 'Đang đọc kiến thức và biên soạn câu hỏi phù hợp.', generate: 'Tạo câu hỏi', selectLesson: 'Chọn bài trong mục lục (bắt buộc)', editGenerated: 'Xem và sửa câu hỏi AI', approve: 'Duyệt câu', approveAll: 'Duyệt tất cả', unapprove: 'Bỏ duyệt', saveApproved: 'Lưu câu đã duyệt', saved: 'Đã lưu', approved: 'Đã duyệt' },
      room: { join: 'Tham gia phòng quiz', code: 'Mã phòng', nickname: 'Nickname', joining: 'Đang vào phòng...' },
      realtime: { finishedTitle: 'Tổng kết trận đấu', finishedDescription: 'Trận đấu đã kết thúc. Dưới đây là kết quả của cả phòng.', studentFinishedTitle: 'Kết quả của bạn', questions: 'Số câu', players: 'Người chơi', answers: 'Lượt trả lời', accuracy: 'Độ chính xác', rank: 'Hạng', score: 'Điểm', correct: 'Đúng', answered: 'Đã trả lời', newRoom: 'Tạo phòng mới', ended: 'Đã kết thúc' },
      worksheet: { eyebrow: 'PHIẾU BÀI TẬP', title: 'Xuất phiếu làm bài Word', description: 'Chọn câu hỏi trong kho, tạo tự động hoặc tạo mới bằng AI rồi tải phiếu theo mẫu.', subject: 'Môn học', grade: 'Khối lớp', levels: 'Mức độ', lessons: 'Bài học trong mục lục', types: 'Hình thức', multipleChoice: 'Trắc nghiệm', essay: 'Tự luận', search: 'Tìm câu hỏi', autoSelect: 'Tự động chọn', generateAi: 'Tạo mới bằng AI', export: 'Xuất file Word', selected: 'Đã chọn {{count}} câu', noQuestions: 'Chưa có câu hỏi phù hợp.', configure: 'Cấu hình số lượng câu', addRow: 'Thêm dòng', count: 'Số lượng', confirm: 'Xác nhận', titleLabel: 'Tên phiếu', template: 'Mẫu câu hỏi', candidates: 'Câu hỏi phù hợp', generating: 'Đang tạo câu hỏi bằng AI...' },
      accounts: { eyebrow: 'QUẢN TRỊ TÀI KHOẢN', title: 'Quản lý tài khoản', adminDescription: 'Admin xem toàn bộ tài khoản và có thể thay đổi vai trò.', teacherDescription: 'Danh sách học sinh thuộc các lớp bạn đang phụ trách.', empty: 'Chưa có tài khoản phù hợp.', noMatch: 'Không có tài khoản khớp bộ lọc.', name: 'Họ tên', login: 'Email / tên đăng nhập', phone: 'Số điện thoại', role: 'Vai trò', classes: 'Lớp học', status: 'Trạng thái', actions: 'Thao tác', searchName: 'Lọc theo họ tên', searchLogin: 'Lọc theo email / tên đăng nhập', searchPhone: 'Lọc theo số điện thoại', searchClass: 'Lọc theo lớp', filterRole: 'Lọc theo vai trò', filterStatus: 'Lọc theo trạng thái', allRoles: 'Tất cả vai trò', allStatuses: 'Tất cả trạng thái', active: 'Đang hoạt động', inactive: 'Đang tắt', activate: 'Kích hoạt', deactivate: 'Tắt', clearFilters: 'Xóa bộ lọc', promote: 'Nâng thành giáo viên', demote: 'Hạ về học sinh', roles: { admin: 'Quản trị viên', teacher: 'Giáo viên', student: 'Học sinh' } },
      studentAccounts: { eyebrow: 'TÀI KHOẢN HỌC SINH', title: 'Tạo tài khoản học sinh hàng loạt', description: 'Nhập trực tiếp hoặc tải file Excel theo mẫu. Tài khoản sẽ được thêm ngay vào lớp đã chọn.', downloadTemplate: 'Tải file mẫu Excel', importExcel: 'Import Excel', username: 'Tên đăng nhập', password: 'Mật khẩu', name: 'Họ tên', phone: 'Số điện thoại', class: 'Lớp học', chooseClass: 'Chọn lớp quản lý', addRow: 'Thêm dòng', remove: 'Xóa', create: 'Tạo tài khoản', created: 'Đã tạo {{count}} tài khoản', failed: 'Lỗi {{count}} dòng' },
      teacherProfile: { eyebrow: 'HỒ SƠ GIÁO VIÊN', title: 'Thông tin công tác', phone: 'Số điện thoại', school: 'Trường học', noSchool: 'Chưa chọn trường' },
      quizSets: { eyebrow: 'THƯ VIỆN ĐỀ', title: 'Quản lý bộ quiz', description: 'Theo dõi, chỉnh sửa, kích hoạt hoặc tạm ngưng các bộ quiz.', create: 'Tạo bộ quiz', createTitle: 'Tạo bộ quiz mới', editTitle: 'Sửa bộ quiz', save: 'Lưu thay đổi', name: 'Tên bộ quiz', descriptionField: 'Mô tả', subject: 'Môn học', grade: 'Khối lớp', timeLimit: 'Thời gian/câu (giây)', status: 'Trạng thái', active: 'Đang hoạt động', inactive: 'Đang tắt', activate: 'Kích hoạt', deactivate: 'Tắt', delete: 'Xóa', edit: 'Sửa', confirmDelete: 'Bạn có chắc muốn xóa bộ quiz này?', chooseQuestions: 'Chọn câu hỏi từ kho', selectQuestion: 'Hãy chọn ít nhất một câu hỏi.', allSubjects: 'Tất cả môn', allGrades: 'Tất cả khối', allStatuses: 'Tất cả trạng thái', list: 'Danh sách bộ quiz', filteredCount: 'Đang hiển thị {{count}} bộ quiz', clearFilters: 'Xóa bộ lọc', filterName: 'Lọc tên bộ quiz', filterSubject: 'Lọc môn học', filterGrade: 'Lọc khối lớp', questionCount: 'Số câu', actions: 'Thao tác', empty: 'Không có bộ quiz phù hợp.' },
      classes: { eyebrow: 'CỘNG ĐỒNG LỚP HỌC', title: 'Lớp học', description: 'Tạo lớp theo khối, trường và khu vực; quản lý học sinh trong lớp.', create: 'Tạo lớp', createEyebrow: 'THÔNG TIN LỚP', createTitle: 'Tạo lớp mới', editTitle: 'Sửa lớp học', save: 'Lưu thay đổi', edit: 'Sửa', delete: 'Xóa', confirmDelete: 'Bạn có chắc muốn xóa lớp này? Dữ liệu thành viên và bài giao liên quan có thể bị xóa theo.', name: 'Tên lớp', grade: 'Khối lớp', school: 'Trường', province: 'Tỉnh', commune: 'Xã', contactPhone: 'Số điện thoại liên hệ', teacherOptional: 'Giáo viên (không bắt buộc)', noTeacher: 'Chưa phân công giáo viên', chooseSchool: 'Chọn trường', chooseProvince: 'Chọn tỉnh', chooseCommune: 'Chọn xã', noLocation: 'Chưa có địa chỉ', students: 'học sinh', inviteCode: 'Mã mời', manageMembers: 'Quản lý thành viên', addStudentTitle: 'Thêm học sinh vào lớp', studentPlaceholder: 'Email, tên đăng nhập hoặc nickname', inviteStudent: 'Gửi lời mời', pending: 'Chờ học sinh xác nhận', approve: 'Duyệt yêu cầu', reject: 'Từ chối', list: 'Danh sách lớp', filteredCount: 'Đang hiển thị {{count}} lớp', clearFilters: 'Xóa bộ lọc', filterName: 'Lọc tên lớp', filterGrade: 'Lọc khối lớp', filterSchool: 'Lọc trường', filterProvince: 'Lọc tỉnh', filterCommune: 'Lọc xã', filterPhone: 'Lọc số điện thoại', filterTeacher: 'Lọc giáo viên', filterInviteCode: 'Lọc mã mời', status: 'Trạng thái', active: 'Đang hoạt động', inactive: 'Đang tắt', activate: 'Kích hoạt', deactivate: 'Tắt', actions: 'Thao tác', empty: 'Không có lớp phù hợp.' },
      schools: { eyebrow: 'DANH MỤC TRƯỜNG HỌC', title: 'Quản lý danh sách trường học', description: 'Quản lý trường, tỉnh và xã; hỗ trợ nhập và xuất dữ liệu bằng Excel.', add: 'Thêm trường học', edit: 'Sửa', save: 'Lưu thay đổi', create: 'Tạo trường', delete: 'Xóa', confirmDelete: 'Bạn có chắc muốn xóa trường này?', name: 'Tên trường', code: 'Mã trường', address: 'Địa chỉ', province: 'Tỉnh', commune: 'Xã', phone: 'Số điện thoại liên hệ', location: 'Khu vực', teacherCount: 'Giáo viên', status: 'Trạng thái', active: 'Đang hoạt động', inactive: 'Đang tắt', activate: 'Kích hoạt', deactivate: 'Tắt', chooseProvince: 'Chọn tỉnh', chooseCommune: 'Chọn xã', list: 'Danh sách trường', empty: 'Chưa có trường học.', import: 'Import Excel', export: 'Export Excel', dataSchools: 'Trường học', dataProvinces: 'Tỉnh', dataCommunes: 'Xã', actions: 'Thao tác', exportFailed: 'Không thể xuất dữ liệu.' },
      locations: { eyebrow: 'ĐỊA GIỚI HÀNH CHÍNH', title: 'Quản lý tỉnh và xã', description: 'Thêm, sửa, xóa và tra cứu danh mục tỉnh, xã dùng cho địa chỉ trường học.', dataTools: 'Dữ liệu Excel', dataToolsHint: 'Có thể nhập hoặc xuất từng danh mục.', importProvinces: 'Import tỉnh', exportProvinces: 'Export tỉnh', importCommunes: 'Import xã', exportCommunes: 'Export xã', addProvince: 'Thêm tỉnh', editProvince: 'Sửa tỉnh', addCommune: 'Thêm xã', editCommune: 'Sửa xã', save: 'Lưu thay đổi', create: 'Tạo mới', edit: 'Sửa', delete: 'Xóa', name: 'Tên', code: 'Mã', province: 'Tỉnh', chooseProvince: 'Chọn tỉnh', provinceList: 'Danh sách tỉnh', communeList: 'Danh sách xã', filterProvince: 'Lọc theo tên hoặc mã tỉnh', filterCommune: 'Lọc theo tên, mã xã hoặc tỉnh', status: 'Trạng thái', active: 'Đang hoạt động', inactive: 'Đang tắt', activate: 'Kích hoạt', deactivate: 'Tắt', emptyProvince: 'Chưa có tỉnh phù hợp.', emptyCommune: 'Chưa có xã phù hợp.', confirmDeleteProvince: 'Xóa tỉnh sẽ xóa các xã thuộc tỉnh này. Bạn có chắc chắn?', confirmDeleteCommune: 'Bạn có chắc muốn xóa xã này?', exportFailed: 'Không thể xuất dữ liệu.' },
      lessonPicker: { selectAllPage: 'Chọn tất cả trang này', previousPage: 'Trang trước', nextPage: 'Trang sau', page: 'Trang {{current}}/{{total}}', empty: 'Chưa có bài học phù hợp.' },
      typing: {
        eyebrow: 'KỸ NĂNG SỐ · GÕ 10 NGÓN',
        title: 'Luyện gõ phím',
        subtitle: 'Rèn phản xạ 10 ngón theo lộ trình từ hàng phím cơ sở đến Telex và văn bản thực tế.',
        summary: { completed: 'Bài đã hoàn thành', bestWpm: 'WPM tốt nhất', averageAccuracy: 'Độ chính xác TB', stars: 'Tổng số sao', completedValue: '{{completed}}/{{total}}' },
        course: { title: 'Lộ trình luyện tập', description: 'Hoàn thành một bài để mở khóa bài tiếp theo.', best: '{{stars}} sao · {{wpm}} WPM', unit: 'UNIT {{number}}', lessonCount: '{{count}} bài', wpmGoal: '{{wpm}} WPM', accuracyGoal: '≥ {{accuracy}}% chính xác', practice: 'Luyện tập', test: 'Kiểm tra', challenge: 'Thử thách' },
        actions: { course: 'Lộ trình', restart: 'Làm lại', tryAgain: 'Thử lại', continue: 'Tiếp tục', start: 'Bắt đầu', practiceAgain: 'Luyện lại', locked: 'Đang khóa' },
        metrics: { wpm: 'Từ/phút', accuracy: 'Chính xác', time: 'Thời gian', progress: 'Tiến độ' },
        input: { label: 'Gõ nội dung bên dưới', placeholder: 'Bắt đầu gõ để tính thời gian…' },
        hints: { telex: 'Có thể dùng bộ gõ Telex/VNI của thiết bị.', shortcuts: 'Tab: làm lại · Esc: về lộ trình' },
        keyboard: { label: 'Bàn phím ảo', next: 'Phím tiếp theo', space: 'Cách', tab: 'Tab', caps: 'Caps Lock', shift: 'Shift', enter: 'Enter', backspace: 'Xóa lùi' },
        lines: { label: 'Dòng {{current}} trên {{total}}' },
        hands: { label: 'Hướng dẫn tư thế tay', title: 'Tư thế ngón tay', left: 'Bàn tay trái', right: 'Bàn tay phải', shift: 'giữ Shift' },
        fingers: { leftPinky: 'Ngón út trái', leftRing: 'Ngón áp út trái', leftMiddle: 'Ngón giữa trái', leftIndex: 'Ngón trỏ trái', thumb: 'Ngón cái', rightIndex: 'Ngón trỏ phải', rightMiddle: 'Ngón giữa phải', rightRing: 'Ngón áp út phải', rightPinky: 'Ngón út phải' },
        result: { eyebrow: 'HOÀN THÀNH BÀI HỌC', title: 'Tuyệt vời!', stars: 'Đạt {{count}} sao', passed: 'Bạn đã đạt mục tiêu của bài học.', keepPracticing: 'Hãy luyện thêm để đạt ít nhất {{target}}% chính xác.' },
      },
    },
  },
  en: {
    translation: {
      common: { language: 'Language', vietnamese: 'Vietnamese', english: 'English', loading: 'Loading...', retry: 'Retry', close: 'Close', save: 'Save', cancel: 'Cancel', errorTitle: 'Something went wrong', requestFailed: 'The request could not be completed. Please try again.', guest: 'Guest', changeAccount: 'Switch account', signIn: 'Sign in', signOut: 'Sign out', locked: 'Locked', online: 'System online' },
      navigation: { student: 'Student', teacher: 'Teacher', home: 'Home', room: 'Realtime room', assignments: 'My assignments', classes: 'Classes', classList: 'Class list', accounts: 'Account management', schools: 'Schools', locations: 'Province & commune management', typing: 'Touch typing', dashboard: 'Dashboard', questions: 'Question bank', ai: 'AI question builder', quizzes: 'Quiz sets', worksheets: 'Export Word worksheet', reports: 'Reports', admin: 'Administration', assign: 'Assign work', teacherSignIn: 'Teacher sign in' },
      brand: { caption: 'LEARN HAPPILY · REMEMBER LONGER', teacherSpace: 'Teacher space', studentSpace: 'Student space', teacherChip: 'Teacher · {{name}}', studentChip: 'Student · {{name}}' },
      theme: { label: 'Appearance', light: 'Light', dark: 'Dark', useLight: 'Use light theme', useDark: 'Use dark theme' },
      home: { eyebrow: 'INTERACTIVE LEARNING PLATFORM', title: 'Make every question more engaging.', description: 'Practice knowledge, join live quiz rooms with your class, and get results after each challenge.', join: 'Join a quiz room →', learnMore: 'Learn more', realtimeTitle: 'Play in real time', realtimeDescription: 'Join with the code provided by your teacher.', practiceTitle: 'Learn proactively', practiceDescription: 'Review by subject and grade level.', resultTitle: 'See results instantly', resultDescription: 'View your score and progress after each completion.' },
      landing: { eyebrow: 'INTERACTIVE LEARNING · PROGRESS EVERY DAY', title: 'Play quizzes. Practice typing. Grow with confidence.', description: 'Quizzz combines energetic live quizzes with a guided typing path, helping students learn proactively while teachers can track progress with ease.', quizCta: 'Explore quizzes', typingCta: 'Practice typing', cardCaption: 'Learn happily · Remember longer', quizBadge: 'Live quiz', typingBadge: 'Touch typing', quizEyebrow: 'PLAY AND LEARN', quizTitle: 'Live quizzes with your class', quizDescription: 'Join with a room code, answer in real time, and see the leaderboard as soon as the match ends.', quizLink: 'Open student space', typingEyebrow: 'DIGITAL SKILLS', typingTitle: 'Ten-finger typing practice', typingDescription: 'Progress from the home row to practical text with a virtual keyboard, hand guidance, and WPM statistics.', typingLink: 'Open typing path', trustOne: 'Learn at your own pace', trustTwo: 'Clear progress insights', trustThree: 'Works on every device' },
      auth: { eyebrow: 'SIGN IN', title: 'Start learning', registerEyebrow: 'SIGN UP', registerTitle: 'Create a student account', nickname: 'Nickname', nicknamePlaceholder: 'Enter a nickname', username: 'Username', usernameOrEmail: 'Username or email', email: 'Email', phone: 'Phone number', password: 'Password', confirmPassword: 'Confirm password', passwordMismatch: 'Passwords do not match.', register: 'Sign up', haveAccount: 'Already have an account? Sign in', createAccount: 'No account yet? Sign up', loginWithGoogle: 'Sign in with Google', registerWithGoogle: 'Sign up with Google' },
      quiz: { allowRetry: 'Allow retry', showAnswers: 'Show answers after submission', submit: 'Submit quiz', unanswered: '{{count}} questions are unanswered. Submit anyway?', answered: '{{answered}}/{{total}} answered' },
      ai: { title: 'Create questions with AI', generating: 'AI is creating questions...', generatingHint: 'Reading the selected knowledge and preparing suitable questions.', generate: 'Generate questions', selectLesson: 'Select lessons from curriculum (required)', editGenerated: 'Review and edit AI questions', approve: 'Approve question', approveAll: 'Approve all', unapprove: 'Unapprove', saveApproved: 'Save approved questions', saved: 'Saved', approved: 'Approved' },
      room: { join: 'Join quiz room', code: 'Room code', nickname: 'Nickname', joining: 'Joining room...' },
      realtime: { finishedTitle: 'Match summary', finishedDescription: 'The match has ended. Here are the results for the room.', studentFinishedTitle: 'Your result', questions: 'Questions', players: 'Players', answers: 'Answers', accuracy: 'Accuracy', rank: 'Rank', score: 'Score', correct: 'Correct', answered: 'Answered', newRoom: 'Create new room', ended: 'Finished' },
      worksheet: { eyebrow: 'WORKSHEET', title: 'Export Word worksheet', description: 'Select questions from the bank, select automatically, or generate with AI and download a template-based worksheet.', subject: 'Subject', grade: 'Grade', levels: 'Difficulty', lessons: 'Lessons in curriculum', types: 'Question format', multipleChoice: 'Multiple choice', essay: 'Essay', search: 'Find questions', autoSelect: 'Select automatically', generateAi: 'Generate with AI', export: 'Export Word file', selected: '{{count}} questions selected', noQuestions: 'No matching questions found.', configure: 'Set question quantities', addRow: 'Add row', count: 'Quantity', confirm: 'Confirm', titleLabel: 'Worksheet title', template: 'Question template', candidates: 'Matching questions', generating: 'Generating questions with AI...' },
      accounts: { eyebrow: 'ACCOUNT MANAGEMENT', title: 'Account management', adminDescription: 'Admins can view every account and change roles.', teacherDescription: 'Students belonging to the classes you manage.', empty: 'No matching accounts.', noMatch: 'No accounts match the filters.', name: 'Name', login: 'Email / username', phone: 'Phone', role: 'Role', classes: 'Classes', status: 'Status', actions: 'Actions', searchName: 'Filter by name', searchLogin: 'Filter by email / username', searchPhone: 'Filter by phone', searchClass: 'Filter by class', filterRole: 'Filter by role', filterStatus: 'Filter by status', allRoles: 'All roles', allStatuses: 'All statuses', active: 'Active', inactive: 'Inactive', activate: 'Activate', deactivate: 'Deactivate', clearFilters: 'Clear filters', promote: 'Promote to teacher', demote: 'Demote to student', roles: { admin: 'Administrator', teacher: 'Teacher', student: 'Student' } },
      studentAccounts: { eyebrow: 'STUDENT ACCOUNTS', title: 'Bulk student accounts', description: 'Enter accounts directly or import the Excel template. New accounts are added to the selected class.', downloadTemplate: 'Download Excel template', importExcel: 'Import Excel', username: 'Username', password: 'Password', name: 'Name', phone: 'Phone', class: 'Class', chooseClass: 'Choose a managed class', addRow: 'Add row', remove: 'Remove', create: 'Create accounts', created: '{{count}} accounts created', failed: '{{count}} row errors' },
      teacherProfile: { eyebrow: 'TEACHER PROFILE', title: 'Work information', phone: 'Phone', school: 'School', noSchool: 'No school selected' },
      quizSets: { eyebrow: 'QUIZ LIBRARY', title: 'Quiz set management', description: 'Review, edit, activate or deactivate quiz sets.', create: 'Create quiz set', createTitle: 'Create quiz set', editTitle: 'Edit quiz set', save: 'Save changes', name: 'Quiz set name', descriptionField: 'Description', subject: 'Subject', grade: 'Grade', timeLimit: 'Time per question (seconds)', status: 'Status', active: 'Active', inactive: 'Inactive', activate: 'Activate', deactivate: 'Deactivate', delete: 'Delete', edit: 'Edit', confirmDelete: 'Delete this quiz set?', chooseQuestions: 'Choose questions from the bank', selectQuestion: 'Choose at least one question.', allSubjects: 'All subjects', allGrades: 'All grades', allStatuses: 'All statuses', list: 'Quiz set list', filteredCount: 'Showing {{count}} quiz sets', clearFilters: 'Clear filters', filterName: 'Filter quiz set name', filterSubject: 'Filter subject', filterGrade: 'Filter grade', questionCount: 'Questions', actions: 'Actions', empty: 'No matching quiz sets.' },
      classes: { eyebrow: 'CLASS COMMUNITY', title: 'Classes', description: 'Create classes by grade, school and area, then manage students.', create: 'Create class', createEyebrow: 'CLASS DETAILS', createTitle: 'Create a class', editTitle: 'Edit class', save: 'Save changes', edit: 'Edit', delete: 'Delete', confirmDelete: 'Delete this class? Related members and assignments may also be removed.', name: 'Class name', grade: 'Grade', school: 'School', province: 'Province', commune: 'Commune', contactPhone: 'Contact phone', teacherOptional: 'Teacher (optional)', noTeacher: 'No teacher assigned', chooseSchool: 'Choose school', chooseProvince: 'Choose province', chooseCommune: 'Choose commune', noLocation: 'No location', students: 'students', inviteCode: 'Invite code', manageMembers: 'Manage members', addStudentTitle: 'Add students to class', studentPlaceholder: 'Email, username or nickname', inviteStudent: 'Send invitation', pending: 'Waiting for confirmation', approve: 'Approve', reject: 'Reject', list: 'Class list', filteredCount: 'Showing {{count}} classes', clearFilters: 'Clear filters', filterName: 'Filter class name', filterGrade: 'Filter grade', filterSchool: 'Filter school', filterProvince: 'Filter province', filterCommune: 'Filter commune', filterPhone: 'Filter phone', filterTeacher: 'Filter teacher', filterInviteCode: 'Filter invite code', status: 'Status', active: 'Active', inactive: 'Inactive', activate: 'Activate', deactivate: 'Deactivate', actions: 'Actions', empty: 'No matching classes.' },
      schools: { eyebrow: 'SCHOOL DIRECTORY', title: 'School management', description: 'Manage schools, provinces and communes with Excel import and export.', add: 'Add school', edit: 'Edit', save: 'Save changes', create: 'Create school', delete: 'Delete', confirmDelete: 'Are you sure you want to delete this school?', name: 'School name', code: 'School code', address: 'Address', province: 'Province', commune: 'Commune', phone: 'Contact phone', location: 'Location', teacherCount: 'Teachers', status: 'Status', active: 'Active', inactive: 'Inactive', activate: 'Activate', deactivate: 'Deactivate', chooseProvince: 'Choose province', chooseCommune: 'Choose commune', list: 'School list', empty: 'No schools yet.', import: 'Import Excel', export: 'Export Excel', dataSchools: 'Schools', dataProvinces: 'Provinces', dataCommunes: 'Communes', actions: 'Actions', exportFailed: 'Could not export data.' },
      locations: { eyebrow: 'ADMINISTRATIVE AREAS', title: 'Province and commune management', description: 'Create, edit, delete and search provinces and communes used by school addresses.', dataTools: 'Excel data', dataToolsHint: 'Import or export each catalogue separately.', importProvinces: 'Import provinces', exportProvinces: 'Export provinces', importCommunes: 'Import communes', exportCommunes: 'Export communes', addProvince: 'Add province', editProvince: 'Edit province', addCommune: 'Add commune', editCommune: 'Edit commune', save: 'Save changes', create: 'Create', edit: 'Edit', delete: 'Delete', name: 'Name', code: 'Code', province: 'Province', chooseProvince: 'Choose province', provinceList: 'Province list', communeList: 'Commune list', filterProvince: 'Filter by province name or code', filterCommune: 'Filter by commune, code or province', status: 'Status', active: 'Active', inactive: 'Inactive', activate: 'Activate', deactivate: 'Deactivate', emptyProvince: 'No matching provinces.', emptyCommune: 'No matching communes.', confirmDeleteProvince: 'Deleting a province also deletes its communes. Continue?', confirmDeleteCommune: 'Delete this commune?', exportFailed: 'Could not export data.' },
      lessonPicker: { selectAllPage: 'Select all on this page', previousPage: 'Previous page', nextPage: 'Next page', page: 'Page {{current}}/{{total}}', empty: 'No matching lessons.' },
      typing: {
        eyebrow: 'DIGITAL SKILLS · TOUCH TYPING',
        title: 'Typing practice',
        subtitle: 'Build ten-finger reflexes from the home row through Telex and practical Vietnamese text.',
        summary: { completed: 'Lessons completed', bestWpm: 'Best WPM', averageAccuracy: 'Average accuracy', stars: 'Total stars', completedValue: '{{completed}}/{{total}}' },
        course: { title: 'Practice path', description: 'Complete a lesson to unlock the next one.', best: '{{stars}} stars · {{wpm}} WPM', unit: 'UNIT {{number}}', lessonCount: '{{count}} lessons', wpmGoal: '{{wpm}} WPM', accuracyGoal: '≥ {{accuracy}}% accuracy', practice: 'Practice', test: 'Assessment', challenge: 'Challenge' },
        actions: { course: 'Course', restart: 'Restart', tryAgain: 'Try again', continue: 'Continue', start: 'Start', practiceAgain: 'Practice again', locked: 'Locked' },
        metrics: { wpm: 'WPM', accuracy: 'Accuracy', time: 'Time', progress: 'Progress' },
        input: { label: 'Type the text below', placeholder: 'Start typing to begin the timer…' },
        hints: { telex: 'You can use the device Telex/VNI input method.', shortcuts: 'Tab: restart · Esc: return to course' },
        keyboard: { label: 'Virtual keyboard', next: 'Next key', space: 'Space', tab: 'Tab', caps: 'Caps Lock', shift: 'Shift', enter: 'Enter', backspace: 'Backspace' },
        lines: { label: 'Line {{current}} of {{total}}' },
        hands: { label: 'Hand posture guide', title: 'Finger posture', left: 'Left hand', right: 'Right hand', shift: 'hold Shift' },
        fingers: { leftPinky: 'Left pinky', leftRing: 'Left ring finger', leftMiddle: 'Left middle finger', leftIndex: 'Left index finger', thumb: 'Thumb', rightIndex: 'Right index finger', rightMiddle: 'Right middle finger', rightRing: 'Right ring finger', rightPinky: 'Right pinky' },
        result: { eyebrow: 'LESSON COMPLETE', title: 'Great work!', stars: '{{count}} stars earned', passed: 'You reached the lesson goal.', keepPracticing: 'Keep practicing to reach at least {{target}}% accuracy.' },
      },
    },
  },
};

i18n.use(initReactI18next).init({ resources, lng: savedLocale || detectedLocale, fallbackLng: 'vi', interpolation: { escapeValue: false }, returnNull: false, saveMissing: import.meta.env.DEV });

export default i18n;
